name: Deploy Frontend

on:
  workflow_run:
    workflows: ["Build and Push Frontend Image"]
    types:
      - completed

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~

            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env.frontend

            echo "Actualizando imagen del frontend..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/refugio-frontend:latest

            docker rm -f refugio_frontend || true
            echo "Levantando frontend..."
            docker compose up -d frontend

            echo "Deploy completado"
